// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN_v0v-OIAuavMH3yGdDWoScYSTdbz-u4',
    appId: '1:890797414019:web:8a1931296ea832a6106db6',
    messagingSenderId: '890797414019',
    projectId: 'gojo-app-b2497',
    authDomain: 'gojo-app-b2497.firebaseapp.com',
    storageBucket: 'gojo-app-b2497.firebasestorage.app',
    measurementId: 'G-QMQ144HL8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIv4J5WzZkNeOZ9kw6K9eO7lFpSsGjG-g',
    appId: '1:890797414019:android:c7c8d73c8cee0ab7106db6',
    messagingSenderId: '890797414019',
    projectId: 'gojo-app-b2497',
    storageBucket: 'gojo-app-b2497.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgdTX_HcDXDhfoOMpFlCRo1dtP1WS7_pQ',
    appId: '1:890797414019:ios:b2443338952a0feb106db6',
    messagingSenderId: '890797414019',
    projectId: 'gojo-app-b2497',
    storageBucket: 'gojo-app-b2497.firebasestorage.app',
    iosBundleId: 'com.example.goJoUserApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgdTX_HcDXDhfoOMpFlCRo1dtP1WS7_pQ',
    appId: '1:890797414019:ios:b2443338952a0feb106db6',
    messagingSenderId: '890797414019',
    projectId: 'gojo-app-b2497',
    storageBucket: 'gojo-app-b2497.firebasestorage.app',
    iosBundleId: 'com.example.goJoUserApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN_v0v-OIAuavMH3yGdDWoScYSTdbz-u4',
    appId: '1:890797414019:web:42668586deaf390d106db6',
    messagingSenderId: '890797414019',
    projectId: 'gojo-app-b2497',
    authDomain: 'gojo-app-b2497.firebaseapp.com',
    storageBucket: 'gojo-app-b2497.firebasestorage.app',
    measurementId: 'G-7DC7YFBPQV',
  );
}
